categories:
    - Fastq Manipulation
description: This is a commandline utility to remove exact duplicate reads from paired-end fastq files.
homepage_url: https://github.com/mvdbeek/dedup_hash
long_description: |
      This is a commandline utility to remove exact duplicate reads from
      paired-end fastq files. Reads are assumed to be in 2 separate files. Read
      sequences are then concatenated and a short hash is calculated on the
      concatenated sequence. If the hash has been previsouly seen the read will
      be dropped from the output file. This means that reads that have the same
      start and end coordinate, but differ in lengths will not be removed (but
      those will be "flattened" to at most 1 occurence).  This algorithm is
      very simple and fast, and saves memory as compared to reading the whole
      fastq file into memory, such as fastuniq does.

name: dedup_hash
owner: mvdbeek
remote_repository_url: https://github.com/mvdbeek/dedup_hash
type: unrestricted
